### ISSUE TITLE
Is system reboot necessary

### ISSUE THREAD

**Issue by sk8nfool** [winterheart/broadcom-bt-firmware#21]
The Readme.md says to reboot the system after installing the firmware. Is that necessary or can the USB device just be removed and reconnected triggering a firmware load?

**Comment by winterheart** [comment]
Hello.
Generally speaking, reboot is required only first time when you placed firmware into system. I saw some systems that can't load firmware since PCI-E BT device already unsuccessful started and badly initialized.

So, once you properly placed firmware and correctly booted device (and in your case this USB dongle), just reinsert USB device and watch to initialization process. If all is OK, you can freely connect/disconnect USB device any time.
