### ISSUE TITLE
No more bluetooth

### ISSUE THREAD

**Issue by daboynb** [winterheart/broadcom-bt-firmware#33]
Fixed, changed to intel card.

**Comment by winterheart** [comment]
Hello.
Seems you have a combined WiFi+Bluetooth device. You need updated firmware for WiFi part of device. Please see https://github.com/winterheart/broadcom-bt-firmware#notes-about-combined-wifibluetooth-devices section in README.md. Since you have Debian, you need install [firmware-brcm80211](https://packages.debian.org/firmware-brcm80211) in order to place BIN part of firmware. TXT part of firmware can be obtained from NVRAM as described here https://wireless.wiki.kernel.org/en/users/drivers/brcm80211#broadcom_brcmfmac_driver

**Comment by winterheart** [comment]
There also some info that can be useful: https://github.com/winterheart/broadcom-bt-firmware/issues/3#issuecomment-318512097

**Comment by daboynb** [comment]
Thanks for the reply, but none of this fixed the issue. WiFi is working normally and the firmware-brcm80211 is already installed.
Before installing the deb all was working, there's no method to revert? thanks.

**Comment by daboynb** [comment]
Looking inside the /sys/firmware/efi/efivars... I don't have any nvram files.
